### ISSUE TITLE
Quotes.get_timesales needs to check if input symbol exists

### ISSUE THREAD

**Issue by thammo4** [thammo4/tradier#9]
Edit the Quotes.get_timesales method. Implement a conditional check to see if the symbol exists before making the GET requet.

>>> quotes = Quotes(ACCOUNT_NUMBER, AUTH_TOKEN)
>>> quotes.get_timesales('AWKL');
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/requests/models.py", line 960, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thammons/Desktop/msds/tradier/tradier/tradier.py", line 462, in get_timesales
    return pd.json_normalize(r.json()['series']['data']);
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/requests/models.py", line 968, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by thammo4** [comment]
Added error handling, nothing more that can really be done here
